### ISSUE TITLE
Duration display with all timeframes in between

### ISSUE THREAD

**Issue by l7ssha** [BaderEddineOuaich/time_ago_provider#11]
Couldn't find it in docs, it is possible to get duration in format like `9h 54 min 12 sec`? Like with all timeframes in between. I would like to display duration in that format rather than in this case `9h`.

If that's not possible I would like to work on that issue. Wanted to ask if thats in scope of this lib and if its already implemented and I just couldn't find any docs.

**Comment by baderouaich** [comment]
Hello @l7ssha, thank you letting us know about this feature!
this library was made for one priority reason was to generate an approximate elapsed time string. 
adding this feature will result on some major changes which will be a rollback to the existing code. 
although i have tested this code which i think will cover your needs:
```dart
void main() {
  /// Get the timestamp
  final clock = DateTime.now();
  final elapsed = DateTime.now().subtract(Duration(hours: 3, minutes: 10, seconds: 5));
  final deltaTime = clock.millisecondsSinceEpoch - elapsed.millisecondsSinceEpoch;

  // Choose durations you want to use
  final num SECONDS = deltaTime / 1000;
  final num MINUTES = SECONDS / 60;
  final num HOURS = MINUTES / 60;
  final num DAYS = HOURS / 24;
  final num MONTHS = DAYS / 30; 
  final num YEARS = DAYS / 365;

  print('${HOURS.round()%24}h ${MINUTES.round()%60}min ${SECONDS.round()%60}sec');
  // Output: 3h 10min 5sec
}
```
Please feel free to modify the library for your own use to cover your needs. and if you need any help with that please let me know.
Best Regards

**Comment by l7ssha** [comment]
Yeah, I have something like you posted above, but I was thinking that would be cool if this package could do something like that. Thanks for reply. I will soon start a draft PR for this feature then :)
