### ISSUE TITLE
How can i implement?

### ISSUE THREAD

**Issue by mrdulal** [BaderEddineOuaich/time_ago_provider#3]
how can i implement in WP post which are fetching out from API.

**Comment by baderouaich** [comment]
Hi there, if the API provides a time stamp value, simply call <strong>TimeAgo.getTimeAgo(timeStamp);</strong>
if not and you want to convert a Date provided by the API to timestamp, then timestamp to time ago, call <strong>DateTime(ApiDateTime)..millisecondsSinceEpoch</strong> to get the time stamp, then recall <strong>TimeAgo.getTimeAgo(timeStamp)</strong>.
if none of these solutions work for you, please provide more informations about your intents in using the package.
Thanks
